# Generated by Django 3.0.5 on 2020-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifyDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
