# Generated by Django 3.0.5 on 2020-05-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('webSite', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annDate', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(max_length=200, null=True)),
                ('annPeriod', models.CharField(max_length=200)),
                ('perforType', models.CharField(max_length=200, null=True)),
                ('perforContent', models.CharField(max_length=4000, null=True)),
                ('changeReason', models.CharField(max_length=4000, null=True)),
                ('upperLimit', models.CharField(max_length=200, null=True)),
                ('lowerLimit', models.CharField(max_length=200, null=True)),
                ('code', models.ForeignKey(db_column='code', null=True, on_delete=django.db.models.deletion.CASCADE, to='security.BasicInfo')),
            ],
        ),
    ]
