# Generated by Django 3.0.5 on 2020-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='webSite',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
