# Generated by Django 3.0.5 on 2020-05-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_perfortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='code',
            field=models.ForeignKey(db_column='code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='security.BasicInfo'),
        ),
        migrations.CreateModel(
            name='myFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myReason', models.CharField(max_length=200)),
                ('code', models.ForeignKey(db_column='code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='security.BasicInfo')),
            ],
        ),
    ]
