# Generated by Django 3.0.5 on 2020-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200501_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='lastModifyDate',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='webSite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
