# Generated by Django 3.0.5 on 2020-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200503_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavorite',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
